"""Paper <-> artifact contract check. Asserts that the canonical
results/paper_numbers.json (regenerated by make_paper_numbers.py) matches the
headline values displayed in the manuscript. Run after reproduce.sh.

Exit 0 if every checked value agrees, 1 otherwise. No API, no network.
"""
from __future__ import annotations
import json, os, sys

R = os.path.join(os.path.dirname(os.path.abspath(__file__)), "experiments", "results")
d = json.load(open(os.path.join(R, "paper_numbers.json")))

# (label, value-in-artifact, value-shown-in-manuscript)
det = d["rq1_detection"]; rep = d["rq2_repair"]; dis = d["dissection"]
pooled = rep["pooled_B2_vs_B0"]; inter = rep["interaction_regression"]
strat = rep["stratified_by_kind"]; audit = dis["detector_audit"]
deb = d["rq3_debiasing"]; cirq = d["replication"]["cross_sdk_cirq_negative"]

checks = [
    ("models = 18",                 d["models"]["total"], 18),
    ("detection static recall",     det["static"]["recall"], 0.719),
    ("detection LLM recall",        det["llm"]["recall"], 0.781),
    ("detection union recall",      det["union"]["recall"], 0.812),
    ("detection union precision",   det["union"]["precision"], 1.0),
    ("union false positives",       det["false_positives_on_40_negatives"], 0),
    ("pooled B2-B0 wins",           pooled["wins"], 168),
    ("pooled B2-B0 losses",         pooled["losses"], 76),
    ("pooled B2-B0 diff",           pooled["diff"], 0.16),
    ("stratified crash diff",       strat["crash"]["diff"], 0.258),
    ("stratified silent diff",      strat["semantic"]["diff"], -0.093),
    ("interaction slope",           round(inter["slope"], 2), -0.47),
    ("interaction R^2",             round(inter["r2"], 2), 0.40),
    ("interaction zero-crossing",   round(inter["zero_crossing_rho"], 2), 0.84),
    ("detector audit static",       audit["static"]["right_family"], 23),
    ("detector audit LLM",          audit["llm"]["right_family"], 25),
    ("detector audit union",        audit["union"]["right_family"], 26),
    ("B3-B4 leakage gap",           deb["B3_vs_B4_leakage_gap"]["diff"], 0.042),
    ("B3-B2 (n.s.)",                deb["B3_vs_B2"]["diff"], 0.012),
    ("B4-B2 erosion",               deb["B4_vs_B2"]["diff"], -0.03),
    ("Cirq Sonnet n = 10",          cirq["claude-sonnet-4-6"]["n"], 10),
    ("Cirq Sonnet 10/10",           cirq["claude-sonnet-4-6"]["B0"], 10),
]

fail = 0
for name, art, paper in checks:
    ok = (art == paper) if not isinstance(paper, float) else abs(art - paper) < 5e-3
    print(f"  {'OK ' if ok else 'XX '} {name:26s} artifact={art}  manuscript={paper}")
    fail += (0 if ok else 1)

print(f"\n{'ALL CONSISTENT' if not fail else str(fail) + ' MISMATCH(ES)'}")
sys.exit(1 if fail else 0)
